name: social_auth_flutter
description: A new Flutter project.
publish_to: "none"
version: 1.0.3+3

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  imagewidget: ^0.0.5
  adaptive_theme: ^3.1.1
  path_provider: ^2.0.11

  # Dependency_injection
  get_it: ^7.2.0

  # Core
  rxdart: ^0.27.3
  equatable: ^2.0.3
  collection: ^1.16.0
  intl: ^0.17.0
  universal_platform: ^1.0.0+1
  clipboard: ^0.1.3

  # state management
  flutter_bloc: ^8.1.1
  # Local database
  shared_preferences: ^2.0.13

  # Network client
  dio: ^4.0.6
  bot_interceptor: ^0.0.6
  retrofit: ^3.0.1+1
  freezed_annotation: ^2.1.0

  json_annotation: ^4.5.0
  top_snackbar_flutter: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # flutter packages pub run build_runner build --delete-conflicting-outputs
  retrofit_generator:
  build_runner: 2.1.11
  json_serializable: ^6.1.4
  freezed: ^2.1.0+1
  
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/img/dark/
    - assets/img/light/
    - assets/icon/